### ISSUE TITLE
mexh wavelet

### ISSUE THREAD

**Issue by masoudpz** [t-vi/pytorch-tvmisc#1]
Hi,How can i use mexh from your codes?
can you show me a sample for mexh wavelet?

**Comment by t-vi** [comment]
Hi,

the [Mexican hat wavelet](https://en.wikipedia.org/wiki/Mexican_hat_wavelet) is a continuous wavelet, so you cannot use it in a discrete wavelet transform directly.
If you need just one convolution, you could discretise the wavelet on some grid and use that in the convolution. Likely, you will need rather large kernel widths (and have more boundary issues / need for padding).
Do you have a particular use case in mind?

Best regards

Thomas

**Comment by masoudpz** [comment]
thanks for your response,
i want to use mexhat for cwssim implementation. i want to convolve a matrix  with mexhat kernel.

**Comment by t-vi** [comment]
I'm afraid this is out of scope for now.
