### ISSUE TITLE
The expanded size of the tensor (100) must match the existing size (3) at non-singleton dimension 1.

### ISSUE THREAD

**Issue by fsalmasri** [t-vi/pytorch-tvmisc#3]
So I added `unsqueeze_(1)`  to each max and mean function. maybe it is the new version difference

**Comment by t-vi** [comment]
Thank you for sharing your experience. Which notebook are you using and where did you need to add it?

**Comment by fsalmasri** [comment]
https://github.com/t-vi/pytorch-tvmisc/blob/master/wasserstein-distance/Pytorch_Wasserstein.ipynb

I'm testing it on histogram distance. but I'm not sure it could help unless I found a way to make it work on minibatches. right now the value is on all the stack as I see.

**Comment by t-vi** [comment]
The numerical stability of the batch approach there is not so good. I did implement a better way at some point but never got around to publishing it.

**Comment by fsalmasri** [comment]
maybe I can test it on a single minibatch tho, what I have seen until now that it is very slow funciton and maybe need to be implemented differently such as converting most of the functions into kernels.

**Comment by fsalmasri** [comment]
maybe I can test it on a single minibatch tho, what I have seen until now that it is very slow funciton and maybe need to be implemented differently such as converting most of the functions into kernels.

**Comment by t-vi** [comment]
So the updated notebook explicitly handles batches. :)
