### ISSUE TITLE
Problem with scripting the model

### ISSUE THREAD

**Issue by Midhilesh29** [t-vi/pytorch-tvmisc#8]
Hi Sir,

I have started learning torchscript and your blog was a great source to understand JIT. I tried to run the notebook pytorch_automatic_optimization_jit.ipynb but I am unable to run the c++, CUDA, CPU kernels also I am unable to get the similar graph present in the notebook. I have attached the link of the colab, I am working with.

**I request you to help me with this problem**

[Colan Notebook](https://colab.research.google.com/drive/1TcHasI6b0VkLvmepTXFyl0IWj-02iGQ5#scrollTo=dSZFfUfmdyly)

**Comment by t-vi** [comment]
Seems like a colab problem to me. I'm not sure how to debug it.
